theme {
    color_scheme = /usr/share/color-schemes/Breeze.colors
    icon_theme = Papirus
    style = Breeze
    font_fixed = Cascadia Code
    font_fixed_size = 11
    font = Noto Sans
    font_size = 10
}
